import { Link } from "react-router-dom";
import { figureIndex, headlineFacts } from "../data/figureIndex";
import ModelBlockDiagram from "../components/ModelBlockDiagram";
import AssumptionBox from "../components/AssumptionBox";

export default function Home() {
  return (
    <div className="space-y-8">
      <section className="space-y-3">
        <span className="pill">teaching site</span>
        <h1>
          A Bang-Bang Fractional-N Digital PLL with a Feedback DTC
        </h1>
        <p>
          This site walks through a behavioral model of the digital PLL
          architecture studied in Tasca <i>et al.</i>, IEEE JSSC vol. 46
          no. 12, pp. 2745–2758, Dec. 2011. We do not reproduce any of the
          paper&apos;s figures or text; every plot here is generated by our
          own Python simulator under <code>sim/</code> and every block
          diagram is hand-drawn from the model.
        </p>
      </section>

      <section className="card space-y-3">
        <h2 className="!mt-0">Paper headline numbers</h2>
        <p className="text-sm text-slate-600">
          From the publicly available abstract and a 2024 IEEE-CAS tutorial
          that cites the paper. We have not yet read the full PDF.
        </p>
        <dl className="grid grid-cols-2 gap-3 text-sm md:grid-cols-4">
          {Object.entries(headlineFacts).map(([k, v]) => (
            <div key={k} className="rounded-lg bg-slate-50 p-3">
              <dt className="text-xs uppercase text-slate-500">{k}</dt>
              <dd className="mt-1 font-mono text-slate-800">{v}</dd>
            </div>
          ))}
        </dl>
      </section>

      <section className="space-y-3">
        <h2>System-level block diagram</h2>
        <p>
          The PLL uses a single-bit time-to-digital converter (the
          bang-bang phase detector) plus a digital-to-time converter in the
          feedback path. The DTC pre-cancels the integer-divider
          quantization error so that, in lock, the BBPD sees only the
          residual noise sources.
        </p>
        <ModelBlockDiagram />
      </section>

      <section className="space-y-3">
        <h2>Pages</h2>
        <ul className="grid gap-3 sm:grid-cols-2">
          {figureIndex.map((f) => (
            <li key={f.slug} className="card !p-4">
              <Link to={`/${f.slug}`} className="!no-underline">
                <div className="flex items-center gap-2">
                  <span className="pill">{f.paperFigGuess}</span>
                  <span className="pill">{f.status}</span>
                </div>
                <h3 className="!mt-2 !text-base">{f.title}</h3>
                <p className="mt-1 text-sm text-slate-600">{f.oneLiner}</p>
              </Link>
            </li>
          ))}
        </ul>
      </section>

      <AssumptionBox kind="warn" title="Reading this site honestly">
        <p>
          The simulator&apos;s numerical agreement with the paper&apos;s
          560 fs RMS jitter target is coincidental: the DCO phase-noise
          template is an estimated guess. The model demonstrates the
          architecture and the noise-cancellation principle, not a chip.
        </p>
      </AssumptionBox>
    </div>
  );
}
