import { getPageBySlug } from "../data/figureIndex";
import PageLayout from "../components/PageLayout";
import CodeBlock from "../components/CodeBlock";
import { Inline } from "../components/EquationBlock";
import AssumptionBox from "../components/AssumptionBox";

const meta = getPageBySlug("mod-pll-model")!;

export default function ModPllModel() {
  return (
    <PageLayout meta={meta}>
      <section>
        <h2 className="!mt-0">Purpose</h2>
        <p>
          The closed-loop simulator. Pre-generates noise sequences,
          instantiates every block, then runs one for-loop with one
          sample per reference cycle. Everything we&apos;ve seen so far
          plugs into this loop.
        </p>
      </section>

      <section>
        <h2>The state schema</h2>
        <CodeBlock
          language="python"
          filename="sim/pll_model.py"
          lineRange="42-58"
          startLine={42}
          code={`@dataclass
class SimResults:
    t_ref: np.ndarray
    t_div: np.ndarray
    t_div_eff: np.ndarray
    e_bbpd: np.ndarray
    s_bbpd: np.ndarray
    u: np.ndarray
    m: np.ndarray
    e_dsm: np.ndarray
    tau_dtc: np.ndarray
    f_dco: np.ndarray
    g_hat: np.ndarray
    params: PLLParams
    alpha: float
    lms_enabled: bool`}
        />
        <p>
          Every per-cycle observable is recorded so any post-processing
          (PSD, jitter integration, spur detection, parameter sweeps) can
          run without re-simulating. With <code>n_cycles=200_000</code>
          that&apos;s ~10 MB of arrays — small enough to live in memory.
        </p>
      </section>

      <section>
        <h2>Noise sources, generated once at the start</h2>
        <CodeBlock
          language="python"
          filename="sim/pll_model.py"
          lineRange="100-118"
          startLine={100}
          code={`    rng = np.random.default_rng(params.rng_seed)
    n = params.n_cycles
    T_ref = params.T_ref

    # ----- Pre-generated noise -----
    if enable_ref_noise and params.ref_jitter_rms_s > 0:
        ref_jitter = rng.normal(0.0, params.ref_jitter_rms_s, n)
    else:
        ref_jitter = np.zeros(n)

    if enable_dco_pn:
        phi_dco_excess = generate_pn_sequence(
            n, params.f_ref,
            params.dco_pn_freqs_hz, params.dco_pn_levels_dbchz, rng)
    else:
        phi_dco_excess = np.zeros(n)`}
        />
        <p>
          Reference jitter is white in our model, so a per-cycle Gaussian
          draw is correct. DCO excess phase is coloured and generated by
          the IFFT method in <code>sim/phase_noise.py</code>. Both
          sequences are produced before the main loop, so the loop body
          stays pure-deterministic given its inputs.
        </p>
      </section>

      <section>
        <h2>The main loop — annotated</h2>
        <CodeBlock
          language="python"
          filename="sim/pll_model.py"
          lineRange="147-186"
          startLine={147}
          code={`    for k in range(n):
        # 1) Reference edge.
        #    Both the divider and the reference start aligned at t = 0;
        #    the FIRST emitted divider edge corresponds to the FIRST
        #    post-zero reference edge at t = T_ref, so index from 1.
        t_ref_k = (k + 1) * T_ref + ref_jitter[k]

        # 2) DSM step (modulus for this cycle + residue used by DTC)
        m_k, e_dsm_k = dsm.step(alpha)
        D_k = fdiv.cycles(m_k)

        # 3) DCO advance; convert injected phase noise (rad) to time (s)
        f_dco_k = dco.frequency(u)
        dt_pn = phi_dco_excess[k] * inv_2pi_f_dco_nom
        t_div_k = t_div_prev + D_k / f_dco_k + dt_pn

        # 4) DTC delay. The DSM residue is pre-scaled by g_hat;
        #    in steady state g_hat -> 1/(1 + gain_err).
        tau_target = g_hat * e_dsm_k * params.T_dco_nominal if enable_dtc else 0.0
        tau_dtc_k = float(dtc.apply(tau_target))
        t_div_eff_k = t_div_k + tau_dtc_k

        # 5) BBPD
        e_k = t_div_eff_k - t_ref_k
        s_k = bbpd.decide(e_k)

        # 6) LMS update of DTC gain coefficient (before loop filter so
        #    g_hat[k] is the value used at step k).
        if enable_lms:
            g_hat = g_hat - lms_mu * s_k * e_dsm_k

        # 7) Loop filter -> new DCO control word
        u = lpf.step(s_k)`}
        />
      </section>

      <section>
        <h2>The off-by-one that wasted an hour</h2>
        <p>
          Note line 151: <code>(k + 1) * T_ref</code>, not
          <code> k * T_ref</code>. The first divider edge happens at
          <Inline tex="\,t \approx D_0/f_{DCO}\approx T_{ref}\," />, not
          at <code>t = 0</code>. If we compare it against
          <code> k*T_ref = 0 </code> we get a constant ~25 ns bias error,
          BBPD saturates to <code>+1</code> forever, and the loop never
          locks. The fix is a one-character change; the diagnosis took
          half an hour.
        </p>
        <p>
          This is the kind of bug behavioral simulators are uniquely
          susceptible to. A real flip-flop doesn&apos;t care what
          &quot;cycle index&quot; is — it just reacts to the next pair of
          edges. Our cycle index is an artificial bookkeeping choice and
          off-by-one mistakes are easy to make.
        </p>
      </section>

      <section>
        <h2>Why the LMS update goes between BBPD and loop filter</h2>
        <p>
          Three subtle ordering decisions in step (6):
        </p>
        <ul className="ml-6 list-disc space-y-2 text-slate-700">
          <li>
            <strong>After BBPD, before LPF.</strong> We need
            <code> s_k </code> to update <code>g_hat</code>, but
            <code> g_hat </code> doesn&apos;t enter the LPF input — only
            DTC drive, which already used the <em>old</em>
            <code> g_hat </code> in step (4). So the order is logically
            simultaneous; we just have to pick one.
          </li>
          <li>
            <strong>Use <code>e_dsm_k</code> not <code>e_dsm_{"{k+1}"}</code>.</strong>
            The regressor must be the same residue the DTC just used.
            Future residues haven&apos;t been generated yet.
          </li>
          <li>
            <strong>Subtract, not add.</strong> Convention sets the sign:
            when DTC over-delays (positive <code>gain_err</code>) and DSM
            residue is positive, BBPD output is positive — product is
            positive — we want <code>g_hat</code> to decrease.
          </li>
        </ul>
      </section>

      <section>
        <h2>Post-processing helper</h2>
        <CodeBlock
          language="python"
          filename="sim/pll_model.py"
          lineRange="61-78"
          startLine={61}
          code={`def excess_phase_at_dco(res, trim_settling=0.5):
    """Return DCO-equivalent excess phase (rad) sampled at f_ref.

    delta[k] = t_div_eff[k] - (k+1)*T_ref
    phi_dco_excess[k] = 2*pi*f_dco_nominal*delta[k]
    """
    p = res.params
    n = len(res.t_div_eff)
    delta = res.t_div_eff - (np.arange(n) + 1) * p.T_ref
    i0 = int(trim_settling * n)
    delta = delta[i0:]
    delta = delta - np.mean(delta)
    return 2.0 * np.pi * p.f_dco_nominal * delta`}
        />
        <p>
          Convert simulator-state to the canonical &quot;DCO excess phase
          sampled at f_ref&quot; form needed by the PSD estimator. Trims
          the lock transient, removes any DC bias, returns radians.
        </p>
      </section>

      <AssumptionBox kind="info">
        Read this file alongside the <strong>Architecture</strong> page —
        the architecture block diagram and this loop body are different
        renderings of the same thing.
      </AssumptionBox>
    </PageLayout>
  );
}
